dist: zesty
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
before_install:
  - echo "deb http://apt.llvm.org/zesty/ llvm-toolchain-zesty main" | sudo tee -a /etc/apt/sources.list.d/llvm-3.9.list
  - echo "deb-src http://apt.llvm.org/zesty/ llvm-toolchain-zesty main" | sudo tee -a /etc/apt/sources.list.d/llvm-3.9.list
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install clang-3.9 lldb-3.9
  - sudo apt-get install clang-3.9 clang-3.9-doc libclang-common-3.9-dev libclang-3.9-dev libclang1-3.9 libclang1-3.9-dbg libllvm-3.9-ocaml-dev libllvm3.9v4 libllvm3.9v4-dbg lldb-3.9 llvm-3.9 llvm-3.9-dev llvm-3.9-doc llvm-3.9-examples llvm-3.9-runtime clang-format-3.9 python-clang-3.9 libfuzzer-3.9-dev
env:
  - LLVM_SYS_39_PREFIX: /usr/lib/llvm-3.9